### ISSUE TITLE
Investigate separating models into separate specification YAML

### ISSUE THREAD

**Issue by hmacdope** [OpenADMET/openadmet_models#22]
Do we want Anvil files to have references to model specifications or contain the models themselves? 

e.g with full specification 

```yaml
...

transform:

split:
  type: ShuffleSplitter
  params:
    train_size: 0.8
    test_size: 0.2
    random_state: 42

feat:
  type: FingerprintFeaturizer
  params:
    fp_type: "ecfp:4"

model:
  type: LGBMRegressorModel
  params:
    model_params:
      alpha: 0.15
      learning_rate: 0.1

train:
  type: SKLearnGridSearchTrainer
  params:
    param_grid:
      alpha: [0.1, 0.15, 0.2]
      learning_rate: [0.1, 0.2, 0.3]



eval:
...
```

or with the model abstracted into a seperate file:

```yaml

model:
  model_yaml: "blah.yaml"
  model: MY_MODEL
```

where `blah.yaml` contains the model specification. 

Anvil will compile the models into a final specification file regardless through templating.
